### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by Natureshadow** [jitsi/jitsi-android#29]
Is the Jitsi for Android project dead?

From what I read from BlueJimp, even the desktop Jitsi client might be dead, or at least in maintenance mode.

Should usage and development offers be directed to another project, or are there any plans to release a stable Jitsi for Android some day?

**Comment by emcho** [comment]
Our Android project has been on hold for more than a year now. 

If you are interested in outting immediate efforts into it you should go ahead and do so.

**Comment by Natureshadow** [comment]
This is not an  answer to my question…

**Comment by emcho** [comment]
It's an answer to your attitude. As for the question: given the nature of open source projects, it is simply impossible to answer. 

If you are interested in the plans of a specific contributor (as opposed to just being controversial) then you should ask them and make your own conclusions as to how satisfactory this answer is to you.

**Comment by SergeyDjam** [comment]
I am also interested in the answer

**Comment by Natureshadow** [comment]
@emcho You are the project owner. And I was referring to the plans of BlueJimp. You are the owner of BlueJimp. Who else would be best to answer my question?

Please do not talk about attitude when you don't like to answer because of your attitude.

**Comment by emcho** [comment]
Now this is a much clearer question that can be answered: At this point in time, BlueJimp (which I am NOT the owner of) has no plans to contribute to Jitsi for Android in the foreseeable future.

Obviously this implies nothing at all as to the plans of other contributors.

As for your attitude George I find it way too demanding for someone with  your (non-existant) level of contributions. You are often controversial and behave as if you are owed attention and answers. Please note that this is not the case. This is not a constructive attitude and other than spoiling a weekend afternoon for me you are achieving nothing else.

**Comment by JohnReedLOL** [comment]
Just because a piece of software is "dead" doesn't mean that it is bad or obsolete. ICE4J hasn't had a commit on its svn repo since 2014, but it is still one of the best, if not the best ICE library for Java. Just because Jitsi for android isn't under active development doesn't mean that you cannot use or tweak the software. Go to https://github.com/jitsi/jitsi-android and give it a chance.

**Comment by Natureshadow** [comment]
@emcho Thanks for your insulting comments.

**Comment by Natureshadow** [comment]
@emcho Thanks for your insulting comments! Now we got to that level, let me talk openly, too:

It is sad to see another free software project being essentially killed by a company that tries to look as though it ran a community project when in fact, it uses its projects as a playground to test out its products. In the end, none of the projects surrounding Jitsi got to a state where it could be called stable or usable. Jitsi for desktop is ancient, has annoying bugs noone cares to reply to, and has obviously been dropped by its creators. It was a cool project, even being promoted as *the* free messaging application by the FSF, but now that the world needs it and people want to use it, it is abandoned, saying that "the community" could continue maintaining it. Same goes for Jitsi on Android, but this project was never really maintained in the first place.

These days, you seem to have moved on to a product called Jitsi-Meet, or other projects using the Jitsi Videobridge - which is pretty cool, but does not solve the issues people have on an every day basis with personal communication. It makes for a good, public video-conferencing tool, but sucks at authentication and private conversation. This is what Jitsi was good at, and this goal is now somewhat gone.

The most saddening part is your view of contributions - there is more to contributing than writing code, which most people can't or do not have time for. User feedback, both questions and bug reports and also criticism, are very important contributions. Unfortunately, you and everyone else in the project failed to reply to any of that. My core attention in free software lies on makign it usible for everyone, with a central view on the needs of children and adolescents, because I am head of an organisation caring for use of technology by children and also because they are great at testdriving UX. If, in your eyes, this is a "non-existent level of contribution", then your views on a community project are more than just a bit askew.

To give you a picture: I spent several years promoting Jitsi among a hell of a lot of people. There were many issues arising, and with a few exceptions, using it was never very successful. Some issues were solved in discussion with project members, most were not. What you an I got is a big group of users who learnt from their Jitsi experience that they'd better use Skype. Well done, Mr. Ivov ☺!

That said, if you feel that users who cannot contribute in the way you like are not permitted to report bugs or criticise your software, then your project is irrelevant at best.

Sorry - I really liked Jitsi (both the rich clients and the web projects), and I really liked some of the people in the project, even despite the issues I mentioned above. But once you get personally insulting, there is not much of that left.

Please, find the time to post a clear statement on what BlueJimp, or whoever leads the projects, has planned in terms of contribution and promotion of its (former) products. Thanks!

**Comment by Natureshadow** [comment]
Oh, now I see:

http://techcrunch.com/2015/04/21/atlassian-acquires-open-source-video-conferencing-company-bluejimp-to-power-hipchats-video-chat/

The whole thing was sold to Atlassian, and they say that they "promise continue to support and develop the open source version of Jitsi going forward".

Yep, we know how that story ends. But at least, it might not be your fault.

**Comment by emcho** [comment]
Now that you've made that clear I expect you not to see you around again. I am sure your contributions will be appreciated in another community. Please do not post here any more.

**Comment by JohnReedLOL** [comment]
@Natureshadow - You can't blame them. Skype uses target advertising on their mobile and desktop apps. When you make an account, Skype asks for your age, gender, maybe even lets your connect to some other services and then uses that information to sell you things (their ads are usually very subtle and small, but they still cause people to buy things). The more users Skype gets, the more money Skype pulls in. This is not the case with Jitsi. Technical support costs money. A developer's time costs money. Free software is not gratis. Ubuntu Linux makes money by advertising for amazon products in its dashboard. Fedora Linux makes money by testing pre-release features for Red Hat Linux. They may be open source, but they must still make money.

**Comment by ibauersachs** [comment]
@Natureshadow Dominik, with your comments you're not only insulting @emcho but also me (and probably @cobratbq). I'm not working for BlueJimp, not for Atlassian. My contributions started as a university project. I agree with you that contribution are not only code, but just reporting bugs and blaming that they haven't been addressed isn't either. If "the world" needs a secure communication application more than ever, then why does nobody come and help?
I personally don't like that all the energy of BlueJimp went into Jitsi Meet, but at the end of the day Emil, Yana, Damian, Boris, Lyubomir, George, Hristo, Yasen, Svetlana, Pawel all need food on the table and a bed to sleep. If Jitsi Meet brings that money rather than the desktop Jitsi, nobody, really nobody, can blame them to follow that path. Jitsi Android AFAIK never brought money, and a paid app wouldn't have been an option, then how can s small company invest resources into it?

I (and Danny) will continue contributing to the desktop client, as you have seen with Danny's recent IRC improvements. There can't be any major changes or improvements though - we both have a day job (we too need food and a bed) and fix things we have the time for.

So unless someone with big money steps up and throws developers in (or finds them for free in the aether), I really don't see how we can make major improvements.

**Comment by SergeyDjam** [comment]
Is it possible to work on jitsi-android such as in goldendict-android? There is a stripped-down free and paid full-featured version. Popularity goldendict very high.

**Comment by dandv** [comment]
Who would be able to upload the latest `apk` to https://download.jitsi.org/jitsi/nightly/android/ ?
